apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ocean-compute-operator
  name: ocean-compute-operator
  namespace: ocean-compute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocean-compute-operator
  template:
    metadata:
      labels:
        app: ocean-compute-operator
    spec:
      containers:
      - name: ocean-compute-operator
        image: ksbek/operator-engine:latest
        imagePullPolicy: Always
        env:
        - name: maxJobDuration
          value: "3600"
        - name: diskGB
          value: "10"
        - name: ramGB
          value: "4"
        - name: IPFS_OUTPUT
          value: https://ipfs.brainstem.dataunion.app
        - name: IPFS_OUTPUT_PREFIX
          value: https://gateway.ipfs.brainstem.dataunion.app/ipfs/
        - name: IPFS_ADMINLOGS
          value: https://ipfs.brainstem.dataunion.app
        - name: IPFS_ADMINLOGS_PREFIX
          value: https://gateway.ipfs.brainstem.dataunion.app/ipfs/
        - name: IPFS_EXPIRY_TIME
          value: "3600"
        - name: STORAGE_CLASS
          value: standard
        - name: LOG_LEVEL
          value: DEBUG
        - name: POD_CONFIGURATION_CONTAINER
          value: oceanprotocol/pod-configuration:v4main
        - name: POD_PUBLISH_CONTAINER
          value: oceanprotocol/pod-publishing:v4main
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-config
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-config
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_HOST
              name: postgres-config
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PORT
              name: postgres-config
        volumeMounts:
        - name: crab-data
          mountPath: /crab-data
      volumes:
      - name: crab-data
        hostPath:
          path: /mnt/crab-data
          type: Directory
      restartPolicy: Always
      serviceAccountName: db-operator
